USE gr_jci;

DROP PROCEDURE IF EXISTS `spGetAddressTypes`;
DROP PROCEDURE IF EXISTS `spGetPhoneTypes`;
DROP PROCEDURE IF EXISTS `spGetStates`;
DROP PROCEDURE IF EXISTS `spGetUserID`;
DROP PROCEDURE IF EXISTS `spGetUserRoles`;
DROP PROCEDURE IF EXISTS `spLoginGetUserID`;
DROP PROCEDURE IF EXISTS `spGetUsersList`;
DROP PROCEDURE IF EXISTS `spCreateUser`;
DROP PROCEDURE IF EXISTS `spCreateAddress`;
DROP PROCEDURE IF EXISTS `spCreatePhoneNumber`;
DROP PROCEDURE IF EXISTS `spCreatePhoneType`;
DROP PROCEDURE IF EXISTS `spCreateAddressType`;