USE gr_jci;

DROP PROCEDURE IF EXISTS `spGetAddressTypes`;
DROP PROCEDURE IF EXISTS `spGetPhoneTypes`;
DROP PROCEDURE IF EXISTS `spGetStates`;
DROP PROCEDURE IF EXISTS `spGetUserID`;
DROP PROCEDURE IF EXISTS `spGetUserRoles`;
DROP PROCEDURE IF EXISTS `spLoginGetUserID`;